# Railway Cloud MySQL Database (for Tux deployment)
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:26738/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=yGWMJvxOXFqQAMPbbuVLVZIpNOwYreks

# Use a custom port for Tux
server.port=9482

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
